Repository AOP-sparta/Trello, pull requests merged in 2024-07, with the labels that each got.

#15 [#4] ✨ feat : Spring Security 세팅
  build.gradle
  src/main/java/sparta/trello/domain/user/UserRepository.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
  src/main/java/sparta/trello/global/security/JwtAuthenticationFilter.java
  src/main/java/sparta/trello/global/security/JwtProvider.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
  src/main/java/sparta/trello/global/security/UserDetailsServiceImpl.java
  src/main/java/sparta/trello/global/security/UserPrincipal.java
  src/main/java/sparta/trello/global/security/handler/AccessDeniedHandlerImpl.java
  src/main/java/sparta/trello/global/security/handler/AuthenticationEntryPointImpl.java
Labels: setting, feat

#21 [#9] ✨ feat : 보드 추가 기능 구현
  src/main/java/sparta/trello/domain/board/Board.java
  src/main/java/sparta/trello/domain/board/BoardController.java
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/domain/board/dto/BoardRequestDto.java
  src/main/java/sparta/trello/domain/board/dto/BoardResponseDto.java
  src/main/java/sparta/trello/global/security/UserPrincipal.java
Labels: feat

#24 [#16] ✨ feat : 회원가입 기능 구현
  http/회원가입, 로그인, 로그아웃.http
  src/main/java/sparta/trello/domain/user/SignupRequestDto.java
  src/main/java/sparta/trello/domain/user/SignupResponseDto.java
  src/main/java/sparta/trello/domain/user/UserController.java
  src/main/java/sparta/trello/domain/user/UserService.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: feat

#33 [#16] ✨ feat : 로그인 기능
  src/main/java/sparta/trello/domain/user/AuthController.java
  src/main/java/sparta/trello/domain/user/AuthService.java
  src/main/java/sparta/trello/domain/user/LoginRequestDto.java
  src/main/java/sparta/trello/domain/user/LoginResponseDto.java
  src/main/java/sparta/trello/domain/user/Token.java
  src/main/java/sparta/trello/domain/user/TokenRepository.java
  src/main/java/sparta/trello/global/security/JwtProvider.java
Labels: feat

#35 [#34] ✨ feat : 로그아웃 기능
  http/회원가입, 로그인, 로그아웃.http
  src/main/java/sparta/trello/domain/user/AuthController.java
  src/main/java/sparta/trello/domain/user/AuthService.java
Labels: feat

#42 [#22] ✨ feat : 보드 조회 기능 구현
  http/보드 생성, 조회.http
  src/main/java/sparta/trello/domain/board/BoardController.java
  src/main/java/sparta/trello/domain/board/BoardRepository.java
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/domain/board/InviteRepository.java
Labels: feat

#50 [#48] 🩹 fix : 보드 조회 중복문제 수정
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/domain/board/InviteRepository.java
Labels: fix

#53 [#36] ✨ feat : 댓글 조회 기능
  src/main/java/sparta/trello/domain/comment/CommentController.java
  src/main/java/sparta/trello/domain/comment/CommentRepository.java
  src/main/java/sparta/trello/domain/comment/CommentService.java
Labels: feat

#49 [#41] 🐛 bugfix : 권한 설정
  src/main/java/sparta/trello/domain/user/AuthController.java
  src/main/java/sparta/trello/domain/user/AuthService.java
  src/main/java/sparta/trello/domain/user/UserController.java
  src/main/java/sparta/trello/domain/user/UserService.java
  src/main/java/sparta/trello/domain/user/dto/LoginRequestDto.java
  src/main/java/sparta/trello/domain/user/dto/LoginResponseDto.java
  src/main/java/sparta/trello/domain/user/dto/SignupRequestDto.java
  src/main/java/sparta/trello/domain/user/dto/SignupResponseDto.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: bug

#59 [#44] ✨ feat : 보드 수정 기능 추가
  http/보드 생성, 조회, 수정.http
  src/main/java/sparta/trello/domain/board/Board.java
  src/main/java/sparta/trello/domain/board/BoardController.java
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/domain/board/Invite.java
  src/main/java/sparta/trello/domain/board/InviteRepository.java
  src/main/java/sparta/trello/domain/board/dto/BoardResponseDto.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
Labels: feat

#62 [#58] ✨ feat : token 재발급 기능 추가
  http/회원가입, 로그인, 로그아웃, 토큰재발급.http
  src/main/java/sparta/trello/domain/user/AuthController.java
  src/main/java/sparta/trello/domain/user/AuthService.java
  src/main/java/sparta/trello/domain/user/TokenRepository.java
  src/main/java/sparta/trello/domain/user/dto/ReissueTokenRequestDto.java
  src/main/java/sparta/trello/domain/user/dto/TokenDto.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
  src/main/java/sparta/trello/global/security/JwtProvider.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: feat

#67 [#57] 🩹 fix : Card seq 칼럼 삭제
  src/main/java/sparta/trello/domain/card/Card.java
  src/main/java/sparta/trello/domain/card/CardRepository.java
  src/main/java/sparta/trello/domain/card/CardService.java
Labels: fix

#68 [#60] 🩹 fix : 보드 조회, 수정 권한 수정
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: fix

#74 [#69] ✨ feat : 보드 삭제 기능
  http/보드 생성, 조회, 수정, 삭제.http
  src/main/java/sparta/trello/domain/board/Board.java
  src/main/java/sparta/trello/domain/board/BoardController.java
  src/main/java/sparta/trello/domain/board/BoardService.java
Labels: feat

#75 [#70] ✨ feat : 보드 유저 초대 기능
  http/보드 생성, 조회, 수정, 삭제, 유저초대.http
  src/main/java/sparta/trello/domain/board/BoardController.java
  src/main/java/sparta/trello/domain/board/BoardService.java
  src/main/java/sparta/trello/domain/board/dto/InviteRequestDto.java
  src/main/java/sparta/trello/domain/board/dto/InviteResponseDto.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
Labels: feat

#79 [#77] ✨ feat : http request 추가
  http/댓글 생성, 조회.http
  http/카드 생성, 조회, 수정, 삭제, 순서이동.http
  http/컬럼 생성, 수정, 조회, 삭제.http
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: feat

#84 [#83] ✨ feat : Front-Back 연동 (Spring)
  src/main/java/sparta/trello/global/config/CorsConfig.java
  src/main/java/sparta/trello/global/security/SecurityConfig.java
Labels: setting

#86 [#81] 🩹 fix : Card 유저 권환 확인 수정
  src/main/java/sparta/trello/domain/card/CardService.java
  src/main/java/sparta/trello/global/exception/ErrorCode.java
Labels: fix

#88 [#87] 🩹 fix : 에러 메세지 출력 수정
  src/main/java/sparta/trello/global/exception/GlobalExceptionHandler.java
Labels: fix

#92 [#91] 🩹 fix : 댓글 작성시 로그인한 유저가 등록되도록 변경
  src/main/java/sparta/trello/domain/comment/CommentController.java
  src/main/java/sparta/trello/domain/comment/CommentService.java
  src/main/java/sparta/trello/domain/comment/dto/CommentRequestDto.java
Labels: fix

#98 [#94] 🩹 fix : 카드 단건 조회 칼럼 수정
  src/main/java/sparta/trello/domain/card/CardController.java
  src/main/java/sparta/trello/domain/card/CardService.java
  src/main/java/sparta/trello/domain/card/dto/FindCardResponseDto.java
Labels: fix

#102 [#101] 🩹 fix : 카드 기능 admin이나 생성자도 사용 불가능한 문제 수정
  src/main/java/sparta/trello/domain/card/CardService.java
Labels: fix
